// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWFVwAnvEyiKkk5APF6jIvO3wniG8oLKI',
    appId: '1:567850827737:web:77f3d213bb490b79c9e3c8',
    messagingSenderId: '567850827737',
    projectId: 'house-note-e2e9e',
    authDomain: 'house-note-e2e9e.firebaseapp.com',
    storageBucket: 'house-note-e2e9e.firebasestorage.app',
    measurementId: 'G-SP05LXHWXZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGz-a8BIg2jGq9BuFHbrpWENgEz2FbAUU',
    appId: '1:567850827737:android:56b35f99a3a8da53c9e3c8',
    messagingSenderId: '567850827737',
    projectId: 'house-note-e2e9e',
    storageBucket: 'house-note-e2e9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdHKmphWQ86roOGeMr3QDa1_t4a6eU2v0',
    appId: '1:567850827737:ios:65a6a25a755cbdeac9e3c8',
    messagingSenderId: '567850827737',
    projectId: 'house-note-e2e9e',
    storageBucket: 'house-note-e2e9e.firebasestorage.app',
    androidClientId: '567850827737-2eifg1fh3268aoslqgralk2onrgs8bvg.apps.googleusercontent.com',
    iosClientId: '567850827737-mkkgfnspnbk089a4c9bgv2nck0tgi864.apps.googleusercontent.com',
    iosBundleId: 'com.ruby444.houseNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdHKmphWQ86roOGeMr3QDa1_t4a6eU2v0',
    appId: '1:567850827737:ios:9f8f01c1a6b8eb16c9e3c8',
    messagingSenderId: '567850827737',
    projectId: 'house-note-e2e9e',
    storageBucket: 'house-note-e2e9e.firebasestorage.app',
    androidClientId: '567850827737-2eifg1fh3268aoslqgralk2onrgs8bvg.apps.googleusercontent.com',
    iosClientId: '567850827737-q6f95t09hf5fjqhvv3lhf2l6r6d01ksv.apps.googleusercontent.com',
    iosBundleId: 'com.example.houseNote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWFVwAnvEyiKkk5APF6jIvO3wniG8oLKI',
    appId: '1:567850827737:web:a8eb8c566ed9cd24c9e3c8',
    messagingSenderId: '567850827737',
    projectId: 'house-note-e2e9e',
    authDomain: 'house-note-e2e9e.firebaseapp.com',
    storageBucket: 'house-note-e2e9e.firebasestorage.app',
    measurementId: 'G-2TK15V9H0F',
  );

}